% sudokoGUI.m
%
% Copyright(c) 2019 Ahmad Bazzi
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files(the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions :
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.
%
%The developer's email is bazziapps@gzixmail.com (for great email, take
% off every 'zix'.)
%

clear all
close all 
clc

%% Create a GUI window 
window = figure('position',[0 0 400 500],...
                'unit','pixels',...
                'name','Sudoko Solver',...
                'visible','on');
movegui(window,'northwest')
%% Create my Sudoku cells
CornerX = 25;
CornerY = 410;
dx = 35;
dy = 35;
for ii = 1:9
    for jj = 1:9
        xPos = CornerX + (jj-1)*dx;
        yPos = CornerY - (ii-1)*dy; 
        sudokugui.X(ii,jj) = uicontrol('unit','pixels',...
                                       'background','w',...
                                       'Style','edit',...
                                       'visible','on',...
                                       'position',[xPos,yPos,dx dy],...
                                       'fontsize',14',...
                                       'fontweight','normal',...
                                       'enable','on',...
                                       'KeyPressFcn',{@cbEntry,window,ii,jj});
    end
end
%% Insert a title textbox
sudokugui.title = uicontrol('Style','text',...  
                            'unit','pixels',...
                            'Fontweight','normal',...   
                            'string','Sudoku Solver',...
                            'Position',[0 455 400 30],...
                            'FontSize',24,...
                            'backgroundcolor',[0.2 0.7 0.7],...
                            'foregroundcolor',[1 1 0]);
%% Insert a SOLVE button
sudokugui.solve = uicontrol('Style','pushbutton',...
                            'callback',{@cbSolve,window},...
                            'string','Solve',...
                            'position',[275 55 100 30],...
                            'backgroundcolor',[0.2 0 0.7],...
                            'foregroundcolor',[0.2 0.9 0]);

%% Insert a CLEAR button
sudokugui.clear = uicontrol('Style','pushbutton',...
                            'callback',{@cbClear,window},...
                            'string','Clear',...
                            'position',[275 15 100 30],...
                            'backgroundcolor',[0.9 0.1 0.2],...
                            'foregroundcolor',[1 0.9 0]);
%% Insert a status bar
sudokugui.status = uicontrol('Style','text',...
                             'unit','pixels',...
                             'string','Hit SOLVE to solve me',...
                             'backgroundcolor',[0.7 0.8 0.7],...
                             'Fontsize',10,...
                             'Position',[25 35 250 50],...
                             'Horizontalalignment','left');
set(window,'UserData',sudokugui)
